desencadenador:
    main

grupo:
    vmImage: ubuntu-latest

variables:
    buildConfiguration: 'Release'

pasos:
    script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'