trigger:
  - main

pool:
  name: 'GitHub-Codespaces-Pool'

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'